/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package restaurantpos;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SuppliersBill extends javax.swing.JFrame {

    public DBGateway dbg;
    Connection connection = null;
    int RowNo;
    /**
     * Creates new form SuppliersBill
     */
    public SuppliersBill() {
        this.dbg = new DBGateway();
            initComponents();
            connection = dbg.connectionTest();
        RowNo = 0;
        //getting category in ComboBox    
        java.sql.Statement stm1 = null;
        ResultSet rs = null;
        try {
            stm1 = connection.createStatement();
            rs = stm1.executeQuery("SELECT * FROM inv_supplier");
            // print the results
            while (rs.next()) {
                //inv_cat_id++;
                jComboBox1.addItem(rs.getString(2));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
            //JOptionPane.showMessageDialog(rootPane, e.toString(),"Error",1);
        }finally
                {
                    DatabaseUtils.close(rs);
                    DatabaseUtils.close(stm1);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tvItem = new javax.swing.JTextField();
        tvQuantity = new javax.swing.JTextField();
        tvUPrice = new javax.swing.JTextField();
        tvTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tvContact = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Supplier Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Unit Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total");

        tvUPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvUPriceKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Contact No.");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Print Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "UnitPrice", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Suppliers Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(109, 109, 109)
                        .addComponent(jButton2)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tvContact)
                                    .addComponent(tvItem, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvUPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tvItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tvQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tvUPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tvTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        tvContact.setText("");
        tvItem.setText("");
        jLabel4.setIcon(new javax.swing.ImageIcon(""));
        //showing the selected item details into textfields
        String SName = "'"+(String) jComboBox1.getSelectedItem()+"'";
        java.sql.Statement stm1 = null;
        ResultSet rs = null;
        try {
            stm1 = connection.createStatement();
            rs = stm1.executeQuery("SELECT * FROM inv_supplier where supp_name = "+SName +"");
            // print the results
            while (rs.next()) {
                tvContact.setText(rs.getString(3));
                tvItem.setText(rs.getString(4));
                
            }
        } catch (Exception e) {
            System.out.println(e.toString());
            //JOptionPane.showMessageDialog(rootPane, e.toString(),"Error",1);
        }finally
                {
                    DatabaseUtils.close(rs);
                    DatabaseUtils.close(stm1);
                }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Date date = Calendar.getInstance().getTime();
         DateFormat formatter = new SimpleDateFormat(" dd/MM/yyyy, hh:mm a");
        String Time = "Date: "+formatter.format(date);
        String Thank = "Thank You For Coming Here!", 
                HD="Cell No: 01834268714, 01731267763.", elseCode = "Powered By ElseCode.", blank = " ";
        String lineS = "-----------Supplier Details------------", 
               line = "---------------------------------------",
        CName = "New Shad Restora", CAddress1 = "Plot# 35, Shonargaon Janopoth Road", 
        CAddress2 = "Sector# 12, Uttara, Dhaka 1230", CAddress3 ="";
        String S[][] = new String[50][5];
        S[0][0] = "Qty";
        S[0][1] = "Description";
        S[0][2] = "UnitP";
        S[0][3] = "Price";
        String SName = (String) jComboBox1.getSelectedItem(), contact = tvContact.getText(), s,
                item = tvItem.getText(), quantity = tvQuantity.getText(), unitprice = tvUPrice.getText(),
        total = tvTotal.getText();
        
        for(int i=0;i<=RowNo;i++){
            
            if((s=String.valueOf(jTable1.getValueAt(i, 0)))!=null){
                S[i][0] =s;
            }
            if((s=String.valueOf(jTable1.getValueAt(i, 1)))!=null){
                S[i][1] =s;
            }
            if((s=String.valueOf(jTable1.getValueAt(i, 2)))!=null){
                S[i][2] =s;
            }
            if((s=String.valueOf(jTable1.getValueAt(i, 3)))!=null){
                S[i][3] =s;
            }
            
        }
        
        try{
            FileWriter filewriter = new FileWriter("E:/POS/supplier.txt");
            PrintWriter out = new PrintWriter(filewriter);
            out.println("           "+CName);
            out.println("  ");
            out.println("   "+CAddress1);
            out.println("     "+CAddress2);
            out.println("  "+CAddress3);
            out.println("     "+Time);
            out.println("  "+"   ");
            out.println(lineS);
            out.println("Name : "+SName);
            out.println("Phone: "+contact);
            out.println("Item : "+item);
            out.println(lineS);
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            
            out.println(line);
            out.println("Item"+"            "+"Qty     "+"UnitP   "+"Price");
            out.println(line);
            for(int j=0;j<=RowNo;j++){
                out.println(S[j][0]+AddSpace(16,S[j][0].length())+S[j][1]+AddSpace(8,S[j][1].length())+S[j][2]+
                        AddSpace(8,S[j][2].length())+S[j][3]);
            }
            
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("  "+"   ");
            out.println("       "+Thank);
            out.println("  "+HD);
            out.println("       "+elseCode);
            out.println(" "+blank);
            out.println(" "+" ");
            out.println(" "+" ");
            out.println(" "+" ");
            out.println();
            
            out.close();
        }catch(IOException ex){
            
        }
        //print the bill file
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.print(new File("E:/POS/supplier.txt"));
        } catch (IOException ex) {
            Logger.getLogger(SellsFrame_Modified.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            for(int j = 0; j < jTable1.getColumnCount(); j++) 
            {
                jTable1.setValueAt("", i, j);
            }
        }
        
        RowNo = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private String AddSpace(int flength, int length)
    {
        String space = "";
        if((flength-length) == 1)
        {
            space=" ";
        }
        else if((flength-length) == 2)
        {
            space="  ";
        }
        else if((flength-length) == 3)
        {
            space="   ";
        }
        else if((flength-length) == 4)
        {
            space="    ";
        }
        else if((flength-length) == 5)
        {
            space="     ";
        }
        else if((flength-length) == 6)
        {
            space="      ";
        }
        else if((flength-length) == 7)
        {
            space="       ";
        }
        else if((flength-length) == 8)
        {
            space="        ";
        }
        else if((flength-length) == 9)
        {
            space="         ";
        }
        else if((flength-length) == 10)
        {
            space="          ";
        }
        else if((flength-length) == 11)
        {
            space="           ";
        }
        else if((flength-length) == 12)
        {
            space="            ";
        }
        else if((flength-length) == 13)
        {
            space="             ";
        }
        else if((flength-length) == 14)
        {
            space="              ";
        }
        else if((flength-length) == 15)
        {
            space="               ";
        }
        else if((flength-length) == 16)
        {
            space="                ";
        }
        else if((flength-length) == 17)
        {
            space="                 ";
        }
        else if((flength-length) == 18)
        {
            space="                  ";
        }
        else if((flength-length) == 19)
        {
            space="                   ";
        }
        return space;
    }
    private void tvUPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvUPriceKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String q = tvQuantity.getText(), up = tvUPrice.getText();
        tvTotal.setText(""+Double.parseDouble(q)*Double.parseDouble(up));
        }
    }//GEN-LAST:event_tvUPriceKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Double TP = 0.0;
        String SName = (String) jComboBox1.getSelectedItem(), contact = tvContact.getText(), 
                item = tvItem.getText(), quantity = tvQuantity.getText(), unitprice = tvUPrice.getText(),
        total = tvTotal.getText();
        jTable1.setValueAt(item, RowNo, 0);
        jTable1.setValueAt(quantity, RowNo, 1);
        jTable1.setValueAt(unitprice, RowNo, 2);
        jTable1.setValueAt(total, RowNo, 3);
        RowNo++;
        
        int k= jTable1.getRowCount(), j, n=RowNo;
        for(j=0;j<RowNo;j++){
            String s = String.valueOf(jTable1.getValueAt(j, 3));
            double p = Double.parseDouble(s);
            //System.out.println(p);
            TP += p;
        }    
        jTable1.setValueAt(" ", n, 0);
        jTable1.setValueAt(" ", n, 1);
        jTable1.setValueAt("Total =", n, 2);
        jTable1.setValueAt(TP, n, 3);
        
        tvQuantity.setText("");
        tvUPrice.setText("");
        tvTotal.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
                connection.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error In Closing DBConnection. Please Ignore it & Click OK.");
            }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
                connection.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error In Closing DBConnection. Please Ignore it & Click OK.");
            }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppliersBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppliersBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppliersBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppliersBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuppliersBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tvContact;
    private javax.swing.JTextField tvItem;
    private javax.swing.JTextField tvQuantity;
    private javax.swing.JTextField tvTotal;
    private javax.swing.JTextField tvUPrice;
    // End of variables declaration//GEN-END:variables
}
